/**
 * Auto-generated by infereval survey export for benchmark 'preframe-golden'.
 *
 * Paste this file into a new Google Apps Script project at
 * https://script.google.com, run createForm(), authorize when
 * prompted, and read the form's URL from the execution log.
 *
 * NOTE: --randomize-items was requested but Google Forms cannot
 * randomize a subset of questions (FormApp.setShuffleQuestions
 * is whole-form, including the expertise question we keep
 * first). The questions are emitted in canonical order.
 */
function createForm() {
  var form = FormApp.create("Analyst recruitment for preframe-golden");
  form.setProgressBar(true);
  form.setCollectEmail(false);

  // Expertise question (kept first, not randomized).
  form.addParagraphTextItem()
      .setTitle("Briefly describe your clinical or domain expertise relevant to these inferences \u2014 your specialty, years in practice, role, and any board certifications.")
      .setRequired(false);

  // Item 1: one
  form.addPageBreakItem()
      .setTitle("Item 1 of 2")
      .setHelpText("Given the following premises, is the conclusion a good diagnostic inference, a bad one, or are you unable to judge?\n\nPremises:\n- the patient has acute dyspnea\n\nConclusion:\n- the patient has cardiogenic pulmonary edema");
  form.addMultipleChoiceItem()
      .setTitle("Item 1 verdict")
      .setChoiceValues(["Good \u2014 follows from premises", "Bad \u2014 does not follow", "Abstain \u2014 cannot judge"])
      .setRequired(true);
  form.addParagraphTextItem()
      .setTitle("Item 1 rationale (optional)")
      .setHelpText("Optional: briefly explain why you chose that verdict (especially helpful if you abstained or rated bad).")
      .setRequired(false);

  // Item 2: two
  form.addPageBreakItem()
      .setTitle("Item 2 of 2")
      .setHelpText("Given the following premises, is the conclusion a good diagnostic inference, a bad one, or are you unable to judge?\n\nPremises:\n- the patient has acute dyspnea\n- the patient has cardiogenic pulmonary edema\n\nConclusion:\n- the patient has ARDS");
  form.addMultipleChoiceItem()
      .setTitle("Item 2 verdict")
      .setChoiceValues(["Good \u2014 follows from premises", "Bad \u2014 does not follow", "Abstain \u2014 cannot judge"])
      .setRequired(true);
  form.addParagraphTextItem()
      .setTitle("Item 2 rationale (optional)")
      .setHelpText("Optional: briefly explain why you chose that verdict (especially helpful if you abstained or rated bad).")
      .setRequired(false);

  Logger.log('Form created:');
  Logger.log(form.getPublishedUrl());
  Logger.log('Edit:');
  Logger.log(form.getEditUrl());
}
