"""Google Forms ``.gs`` Apps Script generator.

Emits a self-contained Google Apps Script (JavaScript source as a
Python string) the recruiter pastes into ``script.google.com`` → New
Project → run. The script calls ``FormApp.create(...)`` to make a
Google Form, populates it with the expertise free-text question + one
MC per item + optional rationale TE, and logs the published URL.

Why Apps Script instead of the Google Forms REST API:

- Apps Script runs in the user's *own* Google account, so there's no
  OAuth client setup, no refresh tokens, no developer-console fiddling
  on infereval's side. The user pastes, hits Run, and Google handles
  authorization with a one-time consent dialog.
- The Google Forms REST API requires a full OAuth2 client; way too
  heavy for a v0.9.0 file-only-export flow.

Randomization caveat: Google Forms' ``FormApp.setShuffleQuestions`` is
*whole-form* — including the expertise question, which we want to keep
at position 0. There's no per-section randomization API. So when
``randomize_items=True``, the generator emits a logged warning at
build time and emits a comment line in the generated ``.gs`` source
explaining the limitation; the questions are emitted in canonical
order.
"""

from __future__ import annotations

import json
import logging
from typing import TYPE_CHECKING

from .render import (
    DEFAULT_EXPERTISE_PROMPT,
    rationale_prompt,
    render_survey_question,
    sanitize_export_tag,
)

if TYPE_CHECKING:
    from ..benchmark import Benchmark
    from ..prompts import VerificationPrompt
    from ..templates import CoherenceFrame

log = logging.getLogger(__name__)


def build_gas_script(
    benchmark: Benchmark,
    *,
    title: str | None = None,
    randomize_items: bool = True,
    include_rationales: bool = True,
    expertise_prompt: str = DEFAULT_EXPERTISE_PROMPT,
    question_form: str = "support",
    coherence_frame: CoherenceFrame | None = None,
    verification_prompt: VerificationPrompt | None = None,
) -> tuple[str, list[dict[str, object]]]:
    """Build a Google Apps Script source string for ``benchmark``.

    The returned ``.gs`` source defines a single ``createForm()``
    function the user runs in script.google.com to generate the form.
    The function logs the form's published URL via ``Logger.log()``;
    the user reads it from the Apps Script execution log.

    Parameters
    ----------
    benchmark
        The benchmark whose items become MC questions.
    title
        Form title. Defaults to ``"Analyst recruitment for <bench.id>"``.
    randomize_items
        When ``True``, emits a comment + warning explaining that Google
        Forms can't randomize a subset; the questions still emit in
        canonical order.
    include_rationales
        When ``True``, each MC is followed by an optional TE rationale
        question.
    expertise_prompt
        Prompt for the survey's first (expertise) free-text question.
    coherence_frame, verification_prompt
        Passed straight through to
        :func:`~infereval.survey.render.render_survey_question`, where
        ALL frame resolution happens. The resolved frame id (uniform
        across items in one export — asserted) is recorded on each
        mapping row.

    Returns
    -------
    gas_source
        The Apps Script source as a Python string. The caller writes
        this to a ``.gs`` file.
    mapping
        Per-item mapping records — same shape as the Qualtrics mapping
        sidecar: ``item_id``, ``verdict_data_export_tag``,
        ``rationale_data_export_tag``, ``was_hashed``,
        ``question_form``, ``frame_id``. The Google
        Forms CSV importer uses the ``[item:<tag>]`` prefix in each
        question title to map column headers back to item ids; this
        mapping is the authoritative reference.
    """
    effective_title = title if title is not None else f"Analyst recruitment for {benchmark.id}"

    if randomize_items:
        log.warning(
            "google_forms.gas.randomize_items_ignored — Google Forms' "
            "FormApp.setShuffleQuestions shuffles the WHOLE form including "
            "the expertise question. Emitting in canonical order; "
            "respondents will see the same item order. Documented in "
            "docs/surveys.md as a platform limitation."
        )

    lines: list[str] = []
    lines.append("/**")
    lines.append(f" * Auto-generated by infereval survey export for benchmark {benchmark.id!r}.")
    lines.append(" *")
    lines.append(" * Paste this file into a new Google Apps Script project at")
    lines.append(" * https://script.google.com, run createForm(), authorize when")
    lines.append(" * prompted, and read the form's URL from the execution log.")
    if randomize_items:
        lines.append(" *")
        lines.append(" * NOTE: --randomize-items was requested but Google Forms cannot")
        lines.append(" * randomize a subset of questions (FormApp.setShuffleQuestions")
        lines.append(" * is whole-form, including the expertise question we keep")
        lines.append(" * first). The questions are emitted in canonical order.")
    lines.append(" */")
    lines.append("function createForm() {")
    lines.append(f"  var form = FormApp.create({json.dumps(effective_title)});")
    lines.append("  form.setProgressBar(true);")
    lines.append("  form.setCollectEmail(false);")
    lines.append("")
    lines.append("  // Expertise question (kept first, not randomized).")
    lines.append("  form.addParagraphTextItem()")
    lines.append(f"      .setTitle({json.dumps(expertise_prompt)})")
    lines.append("      .setRequired(false);")
    lines.append("")

    mapping: list[dict[str, object]] = []
    resolved_frame_ids: set[str | None] = set()
    for i, item in enumerate(benchmark.items, start=1):
        tag, was_hashed = sanitize_export_tag(item.id)
        # v0.9.2: the full prompt (header + premises/conclusion bullets)
        # lives in the PageBreak's helpText / section description.
        # The MC question's TITLE is short ("Item N verdict") because
        # Google Forms uses the question title as the linked-Sheet's
        # CSV column header — long titles make the CSV painful to
        # review. See PR for v0.9.2 and the screenshot that motivated
        # it.
        sq = render_survey_question(
            benchmark,
            item,
            question_form=question_form,
            coherence_frame=coherence_frame,
            verification_prompt=verification_prompt,
        )
        resolved_frame_ids.add(sq.frame_id)
        page_description = sq.full_text()
        verdict_title = f"Item {i} verdict"
        rationale_tag: str | None = None
        if include_rationales:
            rationale_tag = f"{tag}_rationale"

        lines.append(f"  // Item {i}: {item.id}")
        lines.append("  form.addPageBreakItem()")
        lines.append(f"      .setTitle({json.dumps(f'Item {i} of {benchmark.n}')})")
        lines.append(f"      .setHelpText({json.dumps(page_description)});")
        lines.append("  form.addMultipleChoiceItem()")
        lines.append(f"      .setTitle({json.dumps(verdict_title)})")
        lines.append(f"      .setChoiceValues({json.dumps(list(sq.choices))})")
        lines.append("      .setRequired(true);")
        if include_rationales:
            # Short rationale title for the CSV column header. The
            # full guidance prose lives in the question's helpText.
            rationale_title = f"Item {i} rationale (optional)"
            lines.append("  form.addParagraphTextItem()")
            lines.append(f"      .setTitle({json.dumps(rationale_title)})")
            lines.append(f"      .setHelpText({json.dumps(rationale_prompt(question_form))})")
            lines.append("      .setRequired(false);")
        lines.append("")

        mapping.append({
            "item_id": item.id,
            "verdict_data_export_tag": tag,
            "rationale_data_export_tag": rationale_tag,
            "was_hashed": was_hashed,
            "question_form": sq.question_form,
            "frame_id": sq.frame_id,
        })

    # One export = one frame (see qualtrics_qsf.build_qsf).
    assert len(resolved_frame_ids) <= 1, (
        f"survey export resolved multiple frame ids in one export: "
        f"{sorted(str(f) for f in resolved_frame_ids)}"
    )
    log.info(
        "survey.export.frame platform=google_forms benchmark=%s question_form=%s frame_id=%s",
        benchmark.id,
        question_form,
        next(iter(resolved_frame_ids), None),
    )

    lines.append("  Logger.log('Form created:');")
    lines.append("  Logger.log(form.getPublishedUrl());")
    lines.append("  Logger.log('Edit:');")
    lines.append("  Logger.log(form.getEditUrl());")
    lines.append("}")

    return "\n".join(lines) + "\n", mapping
